### ISSUE TITLE
A lot of bug

### ISSUE THREAD

**Issue by OverBrave** [NotReference/PremiumLogin#10]
![image](https://user-images.githubusercontent.com/47111280/80773059-64f3a880-8b61-11ea-9ab2-0aa0909d7cae.png)

Now I'll tell you the bugs I've seen.

1- When 2 people enter, it throws even if the throw is off.

2- When the player activates the premium mode, he logs in authme 2 times.
(2 times coming login message on the chat)

3- Premium players are waiting a lot while entering the server.

4- It does not work with Authmebungee. This causes problems.

**Comment by NotReference** [comment]
> ![image](https://user-images.githubusercontent.com/47111280/80773059-64f3a880-8b61-11ea-9ab2-0aa0909d7cae.png)
> 
> Now I'll tell you the bugs I've seen.
> 
> 1- When 2 people enter, it throws even if the throw is off.
> 
> 2- When the player activates the premium mode, he logs in authme 2 times.
> (2 times coming login message on the chat)
> 
> 3- Premium players are waiting a lot while entering the server.
> 
> 4- It does not work with Authmebungee. This causes problems.

I fixed all these bugs in 1.7.2 (added authmebungee hook too). (Except 2: I didn't remember to fix it sorry. I added it in to-do list for next release.)
