### ISSUE TITLE
1.7.10 - Plugin (Last release)

### ISSUE THREAD

**Issue by Nem-developing** [NotReference/PremiumLogin#11]
![image](https://user-images.githubusercontent.com/54665744/80848178-a728f280-8c12-11ea-8f3e-43c46a32e80d.png)

config : 
![image](https://user-images.githubusercontent.com/54665744/80848199-c3c52a80-8c12-11ea-9c58-3c690ecbf034.png)

servers available : 
![image](https://user-images.githubusercontent.com/54665744/80848248-ed7e5180-8c12-11ea-9af9-20931e0ad4ad.png)

There is no redirections :'(

**Comment by NotReference** [comment]
> ![image](https://user-images.githubusercontent.com/54665744/80848178-a728f280-8c12-11ea-8f3e-43c46a32e80d.png)
> 
> config :
> ![image](https://user-images.githubusercontent.com/54665744/80848199-c3c52a80-8c12-11ea-9c58-3c690ecbf034.png)
> 
> servers available :
> ![image](https://user-images.githubusercontent.com/54665744/80848248-ed7e5180-8c12-11ea-9af9-20931e0ad4ad.png)
> 
> There is no redirections :'(

I am working for 1.7.10 support. Actually isn't hooked. I will warn you when hooked.

**Comment by Nem-developing** [comment]
Great!
