### ISSUE TITLE
Big spam at console

### ISSUE THREAD

**Issue by Volgeop** [NotReference/PremiumLogin#12]
```
>.... [17:40:42 INFO] [PremiumLogin]: ( AuthenticationHandler ) - INFO - Checking LockLogin Status..
>.... [17:40:42 INFO] [PremiumLogin]: ( AuthenticationHandler ) - INFO - Note: Using LockLogin 3.0.2 New API!
>.... [17:40:42 INFO] [PremiumLogin]: ( AuthenticationHandler ) - INFO - Performing auto login to: Renzotom
>.... [17:40:42 INFO] [PremiumLogin]: AuthMeBungee Login Request Successfully Sent.
>.... [17:40:42 INFO] [PremiumLogin]: AuthMeBungee Login Request Successfully Sent.
>.... [17:40:42 INFO] [PremiumLogin]: LOG - The specifed auth server is invaild.
>.... [17:40:42 INFO] [PremiumLogin]: ( AuthenticationHandler ) - INFO - Successfully logged in: user = Renzotom
>.... [17:40:42 INFO] [PremiumLogin]: LOG - Renzotom has been forcelogged (premium mode).
```

Btw this is also annoying... doesn't work after restarting:
`>.... [19:28:27 ERROR] [PremiumLogin]: ERROR - Unable to autologin Renzotom (ignore this, this is not an error [sometimes], is just for block console spam.)`

Hi, why is there so big spam at console? And when players use /premium it doesn't work for them.

**Comment by NotReference** [comment]
> ```
> >.... [17:40:42 INFO] [PremiumLogin]: ( AuthenticationHandler ) - INFO - Checking LockLogin Status..
> >.... [17:40:42 INFO] [PremiumLogin]: ( AuthenticationHandler ) - INFO - Note: Using LockLogin 3.0.2 New API!
> >.... [17:40:42 INFO] [PremiumLogin]: ( AuthenticationHandler ) - INFO - Performing auto login to: Renzotom
> >.... [17:40:42 INFO] [PremiumLogin]: AuthMeBungee Login Request Successfully Sent.
> >.... [17:40:42 INFO] [PremiumLogin]: AuthMeBungee Login Request Successfully Sent.
> >.... [17:40:42 INFO] [PremiumLogin]: LOG - The specifed auth server is invaild.
> >.... [17:40:42 INFO] [PremiumLogin]: ( AuthenticationHandler ) - INFO - Successfully logged in: user = Renzotom
> >.... [17:40:42 INFO] [PremiumLogin]: LOG - Renzotom has been forcelogged (premium mode).
> ```
> 
> 
> Btw this is also annoying... doesn't work after restarting:
> 
> `>.... [19:28:27 ERROR] [PremiumLogin]: ERROR - Unable to autologin Renzotom (ignore this, this is not an error [sometimes], is just for block console spam.)`
> 
> 
> Hi, why is there so big spam at console? And when players use /premium it doesn't work for them.

PremiumLogin is debug-friendly. 

I saw that something went wrong. Did you removed AuthMeBungee from your plugins or disabled / enabled PremiumLogin with external plugins?

**Comment by Volgeop** [comment]
And how could I disable debug? I didn't see it.

And no, I still have AuthMeBungee. And what do you mean with external plugins? It's sure thing that I use also other plugins than premiumlogin

**Comment by Volgeop** [comment]
Hm? @NotReference

**Comment by NotReference** [comment]
> Hm? @NotReference

Please try the 1.6.2 and tell me if your issue is fixed.

**Comment by Volgeop** [comment]
So should I downgrade? But will you fix it in New version too?

**Comment by NotReference** [comment]
> So should I downgrade? But will you fix it in New version too? @NotReference

Yes you should downgrade. I will fix this issue in a new version too.

**Comment by Volgeop** [comment]
With this version I can't join on my 1.15.2 server with 1.16.1 with using ViaVersion.... Without this plugin (version 1.6.2) it normally works. Couldn't you please fix 1.7.2 version as soon as possible?

**Comment by Volgeop** [comment]
How it looks with new ver @NotReference ?

**Comment by NotReference** [comment]
> How it looks with new ver @NotReference ?

I am closing this issue. Check "Something is more often".
