### ISSUE TITLE
Enhancement: Add /premium command confirmation

### ISSUE THREAD

**Issue by zAnonimo** [NotReference/PremiumLogin#14]
Hey! Thanks for making this plugin, it's working as intended so far, I really like it!
Something that I suggest, is to add a confirmation to the /premium command, instead of instantly swapping the account to premium login when they execute it.

I suggest this because sometimes, some troll users tell new players to execute /premium in order to claim something, for example. I guess should be cool if they write /confirm or if they just have to write /premium once again to confirm they want to swap to premium login. Hope you can add this :)

**Comment by NotReference** [comment]
> Hey! Thanks for making this plugin, it's working as intended so far, I really like it!
> 
> Something that I suggest, is to add a confirmation to the /premium command, instead of instantly swapping the account to premium login when they execute it.
> 
> 
> 
> I suggest this because sometimes, some troll users tell new players to execute /premium in order to claim something, for example. I guess should be cool if they write /confirm or if they just have to write /premium once again to confirm they want to swap to premium login. Hope you can add this :)
> 
> 

Thank you for your suggestions. This feature can be interesting, you could probably see it in future releases.

**Comment by NotReference** [comment]
> Hey! Thanks for making this plugin, it's working as intended so far, I really like it!
> Something that I suggest, is to add a confirmation to the /premium command, instead of instantly swapping the account to premium login when they execute it.
> 
> I suggest this because sometimes, some troll users tell new players to execute /premium in order to claim something, for example. I guess should be cool if they write /confirm or if they just have to write /premium once again to confirm they want to swap to premium login. Hope you can add this :)

Thanks you for your feedback!
