### ISSUE TITLE
Cant use whitelist or maintenance mode

### ISSUE THREAD

**Issue by plebexer** [NotReference/PremiumLogin#4]
hey when a player has /premium enabled he is not able to join if the whitelist is on.

**Comment by plebexer** [comment]
or i cant also join if i use /maintenance mode on, (i use luckperms for permissions)
and a plugin to set maintenance mode

**Comment by NotReference** [comment]
> hey when a player has /premium enabled he is not able to join if the whitelist is on.

Hello, i know why, when you use /premium, your uuid changes and the whitelisted uuid is changed too.
You need to re-add him to whitelist or disable for one moment the whitelist, enter (add-you-on-wl) and re-enable them.

**Comment by NotReference** [comment]
> or i cant also join if i use /maintenance mode on, (i use luckperms for permissions)
> and a plugin to set maintenance mode

Set the setup-player-uuid to false if you can't fix. I hope this fix this issue. Reply me if fixed.
