### ISSUE TITLE
What is the RisYP2EY.yml file?

### ISSUE THREAD

**Issue by Kiznaiver27** [NotReference/PremiumLogin#6]
It has the same content as config.yml but I don't know why.
P.S: Excellent plugin

**Comment by NotReference** [comment]
> It has the same content as config.yml but I don't know why.
> P.S: Excellent plugin

Thanks you.

Files with strange name are temp files used for prevent config from lose comments '#' and became harder to use. All temp files will be deleted on plugin load and server shutdown / restart. P.S Only temp files in the PremiumLogin Folder; other files cannot be deleted: I added a dir verification that verify if the file is in the PremiumLogin Folder, else doesn't delete it not even by mistake.
