### ISSUE TITLE
Bungee Setup

### ISSUE THREAD

**Issue by ShazadSkriptREPO** [NotReference/PremiumLogin#7]
Hello i placed PremiumLogin plugin into my bungge plugin folder setup a bit and when i use /premium command it sends me blank line without any text or errors. Authme plugin is on my lobby (SPIGOT) and it has bungeecord set to true

Help please

**Comment by NotReference** [comment]
> Hello i placed PremiumLogin plugin into my bungge plugin folder setup a bit and when i use /premium command it sends me blank line without any text or errors. Authme plugin is on my lobby (SPIGOT) and it has bungeecord set to true
> 
> Help please

Can you send me your config.yml?

**Comment by NotReference** [comment]
> Hello i placed PremiumLogin plugin into my bungge plugin folder setup a bit and when i use /premium command it sends me blank line without any text or errors. Authme plugin is on my lobby (SPIGOT) and it has bungeecord set to true
> 
> Help please

Fixed on PremiumLogin 1.7.1
