### ISSUE TITLE
1.7.10 Minecraft Support

### ISSUE THREAD

**Issue by Nem-developing** [NotReference/PremiumLogin#8]
Hi ! I'm using bungeecord 1.7.10. Can you make the plugin compatible ?
The plugin don't worked :'(
best regards

**Comment by NotReference** [comment]
> Hi ! I'm using bungeecord 1.7.10. Can you make the plugin compatible ?
> The plugin don't worked :'(
> best regards

Hi, support with 1.7.10 is deprecated. I can make a custom version compatible with it. Stay updated.

**Comment by Nem-developing** [comment]
Warn us :)
