### ISSUE TITLE
empty text with commands

### ISSUE THREAD

**Issue by xiorqui** [NotReference/PremiumLogin#9]
hi! i have a problem with the plugins .. i have install and config in my bungeecord server with locklogin (Authme dont work on 1.15.2..) but when i types /premium /premium reload i have an empty text.. just when i use /premiumlogin command i have it tell me :
Premium yes
Using premium launcher no (but i use it)
Default login system Authme (but i have locklogin)
i dont understand all of this..
Thanks

**Comment by NotReference** [comment]
> hi! i have a problem with the plugins .. i have install and config in my bungeecord server with locklogin (Authme dont work on 1.15.2..) but when i types /premium /premium reload i have an empty text.. just when i use /premiumlogin command i have it tell me :
> Premium yes
> Using premium launcher no (but i use it)
> Default login system Authme (but i have locklogin)
> i dont understand all of this..
> Thanks

Fixed in PremiumLogin 1.7.1.
